#!/bin/bash

# variables
cona="commit name: "
brna="branch name: "
repourl="repo url: "
ver="1.0.2"
UNAME=$(uname)

function usage() {
    local u=(
        "Usage:"
        "   cgit -h: help (this output)"
        "   cgit -d: show description"
        "   cgit -v: corgit version"
        "   cgit i: init \".git\" and push origin"
        "   cgit s: status"
        "   cgit sl: show the status of git by list view"
        "   cgit e: push an existing repo"
        "   cgit ph: push and commit"
        "   cgit pl: fetch and pull"
        " "
        "Inside corgit folder "
        "Setup:"
        "   ./setup"
        " "
        "Uninstall:"
        "   ./un"
    )

    printf "%s\n" "${u[@]}"
}

function badUsage() {
    local msg="$1"
    local txt=(
        "For an overview of the command, execute:"
        "cgit h"
    )

    [[ $msg ]] && printf "$msg\n"

    printf "%s\n" "${txt[@]}"
}

function version() {
    local v=(
        "$ver"
    )

    printf "%s\n" "${v[@]}"
}

function desc() {
    local d=(
        "CorGit is a Cli program can automate init git, push commits and pull."
    )

    printf "%s\n" "${d[@]}"
}

initx() {
    # init
    git init
    git add .

    echo "$cona"
    echo " "
    read cn
    git commit -m "$cn"

    echo "$brna"
    echo " "
    read bn
    git branch -M $bn

    echo $repourl
    echo " "
    read url
    git remote add origin $url

    git push -u origin $bn
}

einit() {
    # init
    git init
}

noGit() {
    # if the dic doesn't has .git folder
    echo -e "There's no .git folder... do so want do init it ?\n[Y/n]"
    read -n 1 accept

    if [[ $accept == "" || $accept == "Y" || $accept == "y" ]]; then
        initx
    else
        echo you should accept to init
        exit 0
    fi
}

statusList() {
    # if [ -x "$(command -v colorls)" ]; then
    #     colorls --git-status

    # else
    #     echo -e "there's no colorls, you can install it by type\n gem install colorls"
    # fi

    if [[ "$UNAME" == "Linux" || "$UNAME" == "Darwin" ]]; then
        if [ -x "$(command -v colorls)" ]; then
            colorls -al --git-status

        else
            echo -e "there's no colorls, you can install it by type\n gem install colorls"

        fi
    else
        echo "colorls does not support this system 😔"
    fi
}

pushx() {
    # push
    if [ -d ".git" ]; then
        git status
        git add .
        echo $cona
        echo " "
        read cn
        git commit -m "$cn"
        git push
    else
        noGit
    fi
}

pullx() {
    # pull
    if [ -d ".git" ]; then
        git pull
    else
        einit
    fi
}

status() {
    # status
    if [ -d ".git" ]; then
        git status
    else
        noGit
    fi
}

exrepo() {
    if [ -d ".git" ]; then
        echo "$repourl"
        echo " "
        read url

        echo "$brna"
        echo " "
        read bn

        git remote add origin $url
        git branch -M $bn
        git push -u origin $bn
    else
        einit
    fi
}


while (($#)); do
    case "$1" in

    --help | -h)
        usage
        exit 0
        ;;

    --version | -v)
        version
        exit 0
        ;;

    --desc | --description | -d)
        desc
        exit 0
        ;;

    status | s)
        status
        exit 0
        ;;

    sl)
        statusList
        exit 0
        ;;

    init | i)
        initx
        exit 0
        ;;

    e)
        exrepo
        exit 0
        ;;

    push | ph)
        pushx
        exit 0
        ;;

    pull | pl)
        pullx
        exit 0
        ;;

    *)
        badUsage "Option/command not recognized."
        exit 0
        ;;
    esac
done
