#!/bin/bash

UNAME=$(uname)
cgitUrl=https://raw.githubusercontent.com/Dev-x-Team/corgit/main/cgit
cgitLocLD=/usr/local/bin

successInstall() {
    echo "corgit was installed successfully 🤩, type cgit -h"
}

if [ -x "$(command -v curl)" ]; then
    if [[ "$UNAME" == Linux || "$UNAME" == "Darwin" ]]; then
        if [ -x "$(command -v sudo)" ]; then
            sudo wget -P $cgitLocLD $cgitUrl

            sudo chmod 755 $cgitLocLD/cgit
        else
            wget -P $cgitLocLD $cgitUrl

            chmod 755 $cgitLocLD/cgit
        fi

        successInstall

    elif [[ "$UNAME" == CYGWIN* || "$UNAME" == MINGW* ]]; then
        wget -P /usr/bin $cgitUrl

        successInstall

    else
        echo "😕, Unidentified system..."
        echo "support abdfnx to add corgit to this system"
    fi
fi
