#!/bin/bash

echo -e "do you want to uninstall by manx: recommended or rmrf"
read cli

UNAME=$(uname)

successUninstall() {
    echo "corgit was uninstalled successfully... 👋"
}

manxopa() {
    if [ -x "$(command -v manx)" ]; then
        if [[ "$UNAME" == "Linux" || "$UNAME" == "Darwin" ]]; then
            successUninstall

            sudo manx /usr/local/bin/cgit

        else
            manx /usr/bin/cgit

            successUninstall

        fi
    fi
}

if [[ -x "$(command -v cgit)" || -x "$(command -v corgit)" ]]; then
    if [ "$cli" == "manx" ]; then
        if ! [ -x "$(command -v manx)" ]; then
            echo -e "Error: manx is not installed. do you want to install it?\n[Y/n]"
            read mx

            if [[ $mx == "" || $mx == "Y" || $mx == "y" ]]; then
                if [[ "$UNAME" == "Linux" || "$UNAME" == "Darwin" ]]; then
                    sudo npm i -g @abdfnx/manx

                    manxopa

                else
                    npm i -g @abdfnx/manx

                    manxopa
                fi

            else

                echo "ok, that's means you want to uninstalled it by $rmrf"

                if [[ "$UNAME" == "Linux" || "$UNAME" == "Darwin" ]]; then

                    sudo rm -rf /usr/local/bin/cgit

                    successUninstall

                else

                    rm -rf /usr/bin/cgit
                    successUninstall
                fi

            fi

        else
            if [[ "$UNAME" == "Linux" || "$UNAME" == "Darwin" ]]; then
                sudo manx /usr/local/bin/cgit

                successUninstall

            else

                manx /usr/bin/cgit

                successUninstall

            fi
        fi

    elif [ "$cli" == "rm" ]; then
        if [[ "$UNAME" == "Linux" || "$UNAME" == "Darwin" ]]; then
            sudo rm -rf /usr/local/bin/cgit

            successUninstall

        else

            rm -rf /usr/bin/cgit

            successUninstall

        fi
    fi

else
    echo "There's no corgit 🙃"
fi
